In [1]:
import sys
sys.path.append('/opt/src')

In [2]:
!pwd

/opt/data


In [5]:
import os, yaml
from train import train_net
from db_models import Img, EllipticalParticle
from nn_models import SimpleNet
from dataset import SimulatedParticleDataset
from utils import get_session

config_filepath = os.path.join(os.getcwd(), 'default_config.yaml')
hyper_filepath = os.path.join(os.getcwd(), 'default_hyper.yaml')

with open(config_filepath, "r") as f:
    config = yaml.full_load(f)
with open(hyper_filepath, "r") as f:
    hyper = yaml.full_load(f)

c = {'model_load': '',
            'model_save': os.path.join(os.getcwd(), 'SimpleNetWeights01.pt'),
            'img_dir': os.path.join(os.getcwd(), 'images'),
            'sqlite_path': os.path.join(os.getcwd(), 'particles.db'),
            'db_type': 'SQLITE',
            'checkpoint_load': '',
            'checkpoint_save': '/opt/notebooks/simpnetcheckpt',
            'model_save': '/opt/notebooks/simpnet01.pts'
           }
h = {'learning_rate': .001,
         'batch_size': 10,
         'epochs': 100,
         'loss_weights': [1, 10, 10, 2, 2]
        }


sesh = get_session(config)
imgs = sesh.query(Img).all()


v = [im for j, im in enumerate(imgs) if j % 5 == 0]
t = [im for j, im in enumerate(imgs) if j % 5 != 0]
print(f'Splitting {len(imgs)} images into {len(t)} training samples and {len(v)} validation samples')

trainset = SimulatedParticleDataset(img_objs = t, img_dir =config['img_dir'])
valset = SimulatedParticleDataset(img_objs = v, img_dir =config['img_dir'])

model = SimpleNet()

if config.get('model_load', None):
    model.load_weights(conf['model_load'])
    
train_net(model, trainset, valset, hyper, config)

OperationalError: (sqlite3.OperationalError) no such table: imgs
[SQL: SELECT imgs.id AS imgs_id, imgs.img_filepath AS imgs_img_filepath 
FROM imgs]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [4]:
import torch
foo = torch.tensor([[0,0,1], [1,1,1], [1,2, 2], [3, 2, 1]])

In [12]:
bar = foo.clone()[0,:]

In [13]:
print(bar)

tensor([0, 0, 1])


In [9]:
print(foo)

tensor([[0, 0, 1],
        [1, 1, 1],
        [1, 2, 2],
        [3, 2, 1]])


In [10]:
print(foo[0])

tensor([0, 0, 1])


In [11]:
print(foo[0, 1])

tensor(0)


In [2]:
import torch
MSE = torch.nn.MSELoss()

In [3]:
foo = torch.tensor([0.25, .8, .2, .5, .9, .4])

targ = torch.tensor([0.5, 0.25, 0.1, 0.25, 0.8, 0.9])

In [4]:
l = MSE(foo, targ)

In [5]:
print(l)

tensor(0.1163)


In [11]:
j = MSE(torch.tensor([.25, .25]),torch.tensor([.5, .5]))

In [12]:
print(j)

tensor(0.0625)


In [3]:
import torch
foo = torch.tensor([0, 2, 5, 4, 3, 2, 5, 3])
bar = (foo)

In [4]:
print(foo[[0,1,2,3,4]])

tensor([0, 2, 5, 4, 3])


In [7]:
bar = foo > 3
print(bar)

tensor([False, False,  True,  True, False, False,  True, False])


In [5]:
import yaml

settings = {'model_load': '',
            'model_save': os.path.join(os.getcwd(), 'SimpleNetWeights01.pt'),
            'img_dir': os.path.join(os.getcwd(), 'images'),
            'sqlite_path': os.path.join(os.getcwd(), 'particles.db'),
            'db_type': 'SQLITE',
            'checkpoint_load': '',
            'checkpoint_save': '/opt/notebooks/simpnetcheckpt',
            'model_save': '/opt/notebooks/simpnet01.pts'
           }
hyper = {'learning_rate': .001,
         'batch_size': 10,
         'epochs': 100,
         'loss_weights': [1, 10, 10, 2, 2]
        }

def write_yaml_to_file(py_obj,filename):
    with open(f'{filename}.yaml', 'w',) as f :
        yaml.dump(py_obj,f,sort_keys=False)
        
write_yaml_to_file(settings, 'default_config')
write_yaml_to_file(hyper, 'default_hyper')


In [4]:
foo = sesh.query(EllipticalParticle).all()

NameError: name 'EllipticalParticle' is not defined

In [7]:
import os, yaml
from train import train_net
from db_models import Img, EllipticalParticle
from nn_models import SimpleNet
from dataset import SimulatedParticleDataset
from utils import get_session
import sqlalchemy

config_filepath = os.path.join(os.getcwd(), 'default_config.yaml')
hyper_filepath = os.path.join(os.getcwd(), 'default_hyper.yaml')

with open(config_filepath, "r") as f:
    config = yaml.full_load(f)
with open(hyper_filepath, "r") as f:
    hyper = yaml.full_load(f)

c = {'model_load': '',
            'model_save': os.path.join(os.getcwd(), 'SimpleNetWeights01.pt'),
            'img_dir': os.path.join(os.getcwd(), 'images'),
            'sqlite_path': os.path.join(os.getcwd(), 'particles.db'),
            'db_type': 'SQLITE',
            'checkpoint_load': '',
            'checkpoint_save': '/opt/notebooks/simpnetcheckpt',
            'model_save': '/opt/notebooks/simpnet01.pts'
           }
h = {'learning_rate': .001,
         'batch_size': 10,
         'epochs': 100,
         'loss_weights': [1, 10, 10, 2, 2]
        }


sesh = get_session(config)
imgs = sesh.query(Img).all()

In [10]:
print(config)

{'model_load': '', 'model_save': '/opt/data/simpnet02.pts', 'img_dir': '/opt/data/images', 'sqlite_path': '/opt/data/particles.db', 'db_type': 'SQLITE', 'checkpoint_load': '', 'checkpoint_save': '/opt/data/simpnetcheckpt.pt'}


In [4]:
print(len(imgs))

59000


In [5]:
imgs = sesh.query(Img).filter(len(Img.particles) == 5).all()

TypeError: object of type 'InstrumentedAttribute' has no len()

In [12]:
imgs = sqlalchemy.select(Img, Img.particles).group_by(Img).filter(sqlalchemy.func.count(Img.particles) == 5)

In [13]:
print(imgs)

SELECT imgs.id, imgs.img_filepath, imgs.id = particles.image_id AS anon_1 
FROM imgs, particles 
WHERE count(imgs.id = particles.image_id) = :count_1 GROUP BY imgs.id, imgs.img_filepath


In [30]:
tx = sqlalchemy.sql.text('SELECT * FROM imgs\
                         LEFT JOIN particles on particles.image_id = imgs.id\
                         GROUP BY imgs.id HAVING COUNT(imgs.id) = 7')
foo = sesh.execute(tx).fetchall()
print(len(foo))
print(foo[0])

1837
(4, '/Users/steven/Projects/synthetic_particles/particle_generator/data/images/synth_dist2_4.bmp', 29, 11.974464273274181, 127.12678909735611, 26.856932655872555, 26.856932655872555, 3.447384490557797, 4, 0.06776757467700845, 2)


In [17]:
b = sesh.execute(tx)

In [18]:
print(b)

In [21]:
sesh.execute('SELECT * FROM img')

ArgumentError: Textual SQL expression 'SELECT * FROM img' should be explicitly declared as text('SELECT * FROM img')